# 作業

思考一下我們前面有提到圖片是矩陣，但維度可能會不一樣
例如灰階圖只有兩個維度，RGB 彩圖則有 3 個維度

假如今天我們把 RGB 3 個維度拆開來看會有甚麼不同的效果呢？

In [56]:
import cv2
import numpy as np

## 使用 imread 函式讀取圖片檔案

In [57]:
img = cv2.imread("pictures/lena.png")
print(type(img))
print(img)
print(img.shape)

<class 'numpy.ndarray'>
[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]
(512, 512, 3)


## 使用不同格式載入圖片
<pre><code>
cv2.IMREAD_COLOR # 彩色
cv2.IMREAD_GRAYSCALE   # 灰階
</code></pre>

In [58]:
img_RGB = cv2.imread("pictures/lena.png", cv2.IMREAD_COLOR) # 彩色
img_GRAYSCALE = cv2.imread("pictures/lena.png", cv2.IMREAD_GRAYSCALE) # 灰階
print(img_RGB)

[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]


In [ ]:
## 使用 numpy 分離RGB三色channel
opencv img 圖像為 (512,512,3) 維圖像，分別代表 (row, column, channel) 值
其中channel中每個像素(pixel)的順序為\[B, G, R\]

Ref: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_core/py_basic_ops/py_basic_ops.html#basic-ops


In [59]:
img_B = img_RGB[:, :, 0]
img_G = img_RGB[:, :, 1]
img_R = img_RGB[:, :, 2]
B = np.zeros((512, 512, 3), dtype=np.uint8)
G = np.zeros((512, 512, 3), dtype=np.uint8)
R = np.zeros((512, 512, 3), dtype=np.uint8)
B[:,:,0] = img_B
G[:,:,1] = img_B
R[:,:,2] = img_B
print(img_B)
print(B)

[[125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 ...
 [ 60  60  58 ...  84  76  79]
 [ 57  57  62 ...  79  81  81]
 [ 57  57  62 ...  79  81  81]]
[[[125   0   0]
  [125   0   0]
  [133   0   0]
  ...
  [122   0   0]
  [110   0   0]
  [ 90   0   0]]

 [[125   0   0]
  [125   0   0]
  [133   0   0]
  ...
  [122   0   0]
  [110   0   0]
  [ 90   0   0]]

 [[125   0   0]
  [125   0   0]
  [133   0   0]
  ...
  [122   0   0]
  [110   0   0]
  [ 90   0   0]]

 ...

 [[ 60   0   0]
  [ 60   0   0]
  [ 58   0   0]
  ...
  [ 84   0   0]
  [ 76   0   0]
  [ 79   0   0]]

 [[ 57   0   0]
  [ 57   0   0]
  [ 62   0   0]
  ...
  [ 79   0   0]
  [ 81   0   0]
  [ 81   0   0]]

 [[ 57   0   0]
  [ 57   0   0]
  [ 62   0   0]
  ...
  [ 79   0   0]
  [ 81   0   0]
  [ 81   0   0]]]


## 使用 imshow 顯示圖片

In [60]:
cv2.imshow("RGB", img_RGB)
cv2.imshow("GRAYSCALE", img_GRAYSCALE)
cv2.imshow("img_R", B)
cv2.imshow("img_G", G)
cv2.imshow("img_B", R)
k = cv2.waitKey(0)
if k == 27:
    cv2.destroyAllWindows()