# 範例

透過 SIFT 特徵實作 Brute-Force Matching

In [13]:
import cv2
import numpy as np

# 以灰階方式讀入圖片
img_query = cv2.imread('data/box.png', 0)
img_train = cv2.imread('data/box_in_scene.png', 0)

# 建立 SIFT 物件
sift = cv2.xfeatures2d.SIFT_create()

# 偵測並計算 SIFT 特徵 (keypoints 關鍵點, descriptor 128 維敘述子)
kp_query, des_query = sift.detectAndCompute(img_query, None)
kp_train, des_train = sift.detectAndCompute(img_train, None)
print("key points query length: ", len(kp_query))
print("key points train length: ", len(kp_train))
print(des_query)
print(des_query.shape)

key points query length:  604
key points train length:  969
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 4.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  9.  3. 14.]
 [26.  0.  0. ...  0.  2.  1.]]
(604, 128)


## 基於 SIFT 特徵的暴力比對

- D.Lowe ratio test
- knn 比對

In [18]:
# 建立 Brute-Force Matching 物件
bf = cv2.BFMatcher(cv2.NORM_L2)

# 以 knn 方式暴力比對特徵
# https://docs.opencv.org/master/db/d39/classcv_1_1DescriptorMatcher.html#a378f35c9b1a5dfa4022839a45cdf0e89
matches = bf.knnMatch(des_query, des_train, k=2)
# print(matches)

# 透過 D.Lowe ratio test 排除不適合的配對
candidate = []
for m, n in matches:
    if m.distance < 0.75*n.distance:
        candidate.append([m])

# 顯示配對結果
# https://docs.opencv.org/3.4/d4/d5d/group__features2d__draw.html
img_show = cv2.drawMatchesKnn(img_query, kp_query, img_train, kp_train, candidate, None, flags=2) # or try to set flags = cv2.DrawMatchesFlags_DRAW_RICH_KEYPOINTS


# 顯示圖片
while True:
    cv2.imshow('matches', img_show)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

## BFMatcher.match() V.S. BFMatcher.knnMatch()

* match()回傳最佳配對
* knnMatch() 回傳k個最佳配對

Ref: https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_feature2d/py_matcher/py_matcher.html


## What is Keypoint size in OpenCV?

Ans: https://stackoverflow.com/questions/33421022/keypoints-detected-by-sift-in-opencv-its-size-is-radius-or-diameter-of-relevant
